# Makefile
# Author: Maxwell SLingerland
# Date: Feb 18, 2020
#
# COSC 3750, Homework 4
#
# Makefile for Homework 4

CC = gcc
CFLAGS = -ggdb -Wall

wycat: wycat.c 
		$(CC) $(CFLAGS) wycat.c -o wycat

.PHONY: clean
		I/bin/rm -f wycat